export const CenariosIconsPath: SVGDataIcons = {
  '001-island': import('assets/cenarios/001-island.svg'),
  '002-field': import('assets/cenarios/002-field.svg'),
  '003-lake': import('assets/cenarios/003-lake.svg'),
  '004-desert': import('assets/cenarios/004-desert.svg'),
  '005-rocky mountains': import('assets/cenarios/005-rocky mountains.svg'),
  '006-rainbow': import('assets/cenarios/006-rainbow.svg'),
  '007-autumn': import('assets/cenarios/007-autumn.svg'),
  '008-waterfall': import('assets/cenarios/008-waterfall.svg'),
  '009-forest': import('assets/cenarios/009-forest.svg'),
  '010-mountain': import('assets/cenarios/010-mountain.svg'),
  '011-iceberg': import('assets/cenarios/011-iceberg.svg'),
  '012-sunset': import('assets/cenarios/012-sunset.svg'),
  '013-tulips': import('assets/cenarios/013-tulips.svg'),
  '014-grand canyon': import('assets/cenarios/014-grand canyon.svg'),
  '015-rainbow': import('assets/cenarios/015-rainbow.svg'),
  '016-savannah': import('assets/cenarios/016-savannah.svg'),
  '017-volcano': import('assets/cenarios/017-volcano.svg'),
  '018-mountains': import('assets/cenarios/018-mountains.svg'),
  '019-sea arch': import('assets/cenarios/019-sea arch.svg'),
  '020-windmill': import('assets/cenarios/020-windmill.svg'),
  '021-snowy': import('assets/cenarios/021-snowy.svg'),
  '022-highway': import('assets/cenarios/022-highway.svg'),
  '023-lighthouse': import('assets/cenarios/023-lighthouse.svg'),
  '024-lotus flower': import('assets/cenarios/024-lotus flower.svg'),
  '025-rainbow': import('assets/cenarios/025-rainbow.svg'),
  '026-cow': import('assets/cenarios/026-cow.svg'),
  '027-beach': import('assets/cenarios/027-beach.svg'),
  '028-snowman': import('assets/cenarios/028-snowman.svg'),
  '029-islands': import('assets/cenarios/029-islands.svg'),
  '030-cave': import('assets/cenarios/030-cave.svg'),
  '031-dolphin': import('assets/cenarios/031-dolphin.svg'),
  '032-igloo': import('assets/cenarios/032-igloo.svg'),
  '033-beach house': import('assets/cenarios/033-beach house.svg'),
  '034-abduction': import('assets/cenarios/034-abduction.svg'),
  '035-spring': import('assets/cenarios/035-spring.svg'),
  '036-flamingo': import('assets/cenarios/036-flamingo.svg'),
  '037-castle': import('assets/cenarios/037-castle.svg'),
  '038-sailboat': import('assets/cenarios/038-sailboat.svg'),
  '039-buildings': import('assets/cenarios/039-buildings.svg'),
  '040-hot air balloon': import('assets/cenarios/040-hot air balloon.svg'),
  '041-clouds and sun': import('assets/cenarios/041-clouds and sun.svg'),
  '042-observatory': import('assets/cenarios/042-observatory.svg'),
  '043-cliff': import('assets/cenarios/043-cliff.svg'),
  '044-winter': import('assets/cenarios/044-winter.svg'),
  '045-northern lights': import('assets/cenarios/045-northern lights.svg'),
  '046-undersea': import('assets/cenarios/046-undersea.svg'),
  '047-bridge': import('assets/cenarios/047-bridge.svg'),
  '048-pyramids': import('assets/cenarios/048-pyramids.svg'),
  '049-forest': import('assets/cenarios/049-forest.svg'),
  '050-hills': import('assets/cenarios/050-hills.svg'),
};
