export const Personagens_Icons = [
  { name: 'girl-10', file: '001-girl-10.svg' },
  { name: 'girl-9', file: '002-girl-9.svg' },
  { name: 'boy-20', file: '003-boy-20.svg' },
  { name: 'girl-8', file: '004-girl-8.svg' },
  { name: 'girl-7', file: '005-girl-7.svg' },
  { name: 'bald', file: '006-bald.svg' },
  { name: 'athlete-1', file: '007-athlete-1.svg' },
  { name: 'girl-6', file: '008-girl-6.svg' },
  { name: 'ninja', file: '009-ninja.svg' },
  { name: 'boy-19', file: '010-boy-19.svg' },
  { name: 'boy-18', file: '011-boy-18.svg' },
  { name: 'boy-17', file: '012-boy-17.svg' },
  { name: 'boy-16', file: '013-boy-16.svg' },
  { name: 'boy-15', file: '014-boy-15.svg' },
  { name: 'thief', file: '015-thief.svg' },
  { name: 'boy-14', file: '016-boy-14.svg' },
  { name: 'birthday', file: '017-birthday.svg' },
  { name: 'boy-13', file: '018-boy-13.svg' },
  { name: 'girl-5', file: '019-girl-5.svg' },
  { name: 'girl-4', file: '020-girl-4.svg' },
  { name: 'king', file: '021-king.svg' },
  { name: 'boy-12', file: '022-boy-12.svg' },
  { name: 'costume', file: '023-costume.svg' },
  { name: 'boy-11', file: '024-boy-11.svg' },
  { name: 'boy-10', file: '025-boy-10.svg' },
  { name: 'boy-9', file: '026-boy-9.svg' },
  { name: 'boy-8', file: '027-boy-8.svg' },
  { name: 'girl-3', file: '028-girl-3.svg' },
  { name: 'rich', file: '029-rich.svg' },
  { name: 'punk', file: '030-punk.svg' },
  { name: 'girl-2', file: '031-girl-2.svg' },
  { name: 'boy-7', file: '032-boy-7.svg' },
  { name: 'astronaut', file: '033-astronaut.svg' },
  { name: 'vampire', file: '034-vampire.svg' },
  { name: 'boy-6', file: '035-boy-6.svg' },
  { name: 'viking', file: '036-viking.svg' },
  { name: 'girl-1', file: '037-girl-1.svg' },
  { name: 'athlete', file: '038-athlete.svg' },
  { name: 'girl', file: '039-girl.svg' },
  { name: 'boy-5', file: '040-boy-5.svg' },
  { name: 'wrestler', file: '041-wrestler.svg' },
  { name: 'sheriff', file: '042-sheriff.svg' },
  { name: 'boy-4', file: '043-boy-4.svg' },
  { name: 'futuristic', file: '044-futuristic.svg' },
  { name: 'pirate', file: '045-pirate.svg' },
  { name: 'troglodyte', file: '046-troglodyte.svg' },
  { name: 'boy-3', file: '047-boy-3.svg' },
  { name: 'boy-2', file: '048-boy-2.svg' },
  { name: 'boy-1', file: '049-boy-1.svg' },
  { name: 'boy', file: '050-boy.svg' },
];

export const PersonagenIcons: SVGDataIcons = {
  'girl-10': import('assets/characters/001-girl-10.svg'),
  'girl-9': import('assets/characters/002-girl-9.svg'),
  'boy-20': import('assets/characters/003-boy-20.svg'),
  'girl-8': import('assets/characters/004-girl-8.svg'),
  'girl-7': import('assets/characters/005-girl-7.svg'),
  bald: import('assets/characters/006-bald.svg'),
  'athlete-1': import('assets/characters/007-athlete-1.svg'),
  'girl-6': import('assets/characters/008-girl-6.svg'),
  ninja: import('assets/characters/009-ninja.svg'),
  'boy-19': import('assets/characters/010-boy-19.svg'),
  'boy-18': import('assets/characters/011-boy-18.svg'),
  'boy-17': import('assets/characters/012-boy-17.svg'),
  'boy-16': import('assets/characters/013-boy-16.svg'),
  'boy-15': import('assets/characters/014-boy-15.svg'),
  thief: import('assets/characters/015-thief.svg'),
  'boy-14': import('assets/characters/016-boy-14.svg'),
  birthday: import('assets/characters/017-birthday.svg'),
  'boy-13': import('assets/characters/018-boy-13.svg'),
  'girl-5': import('assets/characters/019-girl-5.svg'),
  'girl-4': import('assets/characters/020-girl-4.svg'),
  king: import('assets/characters/021-king.svg'),
  'boy-12': import('assets/characters/022-boy-12.svg'),
  costume: import('assets/characters/023-costume.svg'),
  'boy-11': import('assets/characters/024-boy-11.svg'),
  'boy-10': import('assets/characters/025-boy-10.svg'),
  'boy-9': import('assets/characters/026-boy-9.svg'),
  'boy-8': import('assets/characters/027-boy-8.svg'),
  'girl-3': import('assets/characters/028-girl-3.svg'),
  rich: import('assets/characters/029-rich.svg'),
  punk: import('assets/characters/030-punk.svg'),
  'girl-2': import('assets/characters/031-girl-2.svg'),
  'boy-7': import('assets/characters/032-boy-7.svg'),
  astronaut: import('assets/characters/033-astronaut.svg'),
  vampire: import('assets/characters/034-vampire.svg'),
  'boy-6': import('assets/characters/035-boy-6.svg'),
  viking: import('assets/characters/036-viking.svg'),
  'girl-1': import('assets/characters/037-girl-1.svg'),
  athlete: import('assets/characters/038-athlete.svg'),
  girl: import('assets/characters/039-girl.svg'),
  'boy-5': import('assets/characters/040-boy-5.svg'),
  wrestler: import('assets/characters/041-wrestler.svg'),
  sheriff: import('assets/characters/042-sheriff.svg'),
  'boy-4': import('assets/characters/043-boy-4.svg'),
  futuristic: import('assets/characters/044-futuristic.svg'),
  pirate: import('assets/characters/045-pirate.svg'),
  troglodyte: import('assets/characters/046-troglodyte.svg'),
  'boy-3': import('assets/characters/047-boy-3.svg'),
  'boy-2': import('assets/characters/048-boy-2.svg'),
  'boy-1': import('assets/characters/049-boy-1.svg'),
  boy: import('assets/characters/050-boy.svg'),
};
